version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: server
    tty: true
    volumes:
      - ./server/app:/app
    ports:
      - "8080:8080"
    networks:
      - server_nw

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: client
    tty: true
    volumes:
      - ./client/app:/app
    ports:
      - "5173:5173"
    networks:
      - server_nw
      - app_nw

networks:
  server_nw:
    external: true
  app_nw:
    external: true

